spring.datasource.url=jdbc:mysql://${MYSQLHOST:shinkansen.proxy.rlwy.net}:${MYSQLPORT:51875}/${MYSQLDATABASE:railway}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:hBFyNIIkuaSaFOUhSdbAXglnOKaqZlDV}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret=trabahanap-super-secret-key-production-2026
jwt.expiration=86400000
server.port=${PORT:8080}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.error.include-message=always